# Health Stats Part 3: Waist 2 Hip Ratios

<!--- Write an explanation of the Waist To Hips Ratio statistic used by health professionals. Please include an explanation of what it is used for, exactly how it is calculated, and how to interpret the results. Note: Formmatting matters. Make this as professional as you can using Markdown.  --->
EDIT THIS MARKDOWN CELL

## Source Data

<!--- Replace the text below with a Markdown bullet list that defines the columns of the CSV file. Be sure to indicate the data type for each column. --->
EDIT THIS MARKDOWN CELL

## Data Import

In [11]:
# Goal: Extract the data from the file

import numpy as np
import pandas as pd


data = pd.read_csv(("w2h_data.csv"), dtype = {"ID": np.int, "Waist": np.float, "Hip": np.float, "Gender": np.str})
print(data)

    ID  Waist   Hip Gender
0    1   30.0  32.0      M
1    2   32.0  37.0      M
2    3   30.0  36.0      M
3    4   33.0  39.0      M
4    5   29.0  33.0      M
5    6   32.0  38.0      M
6    7   33.0  42.0      M
7    8   30.0  40.0      M
8    9   30.0  37.0      M
9   10   32.0  39.0      M
10  11   24.0  35.0      F
11  12   25.0  37.0      F
12  13   24.0  37.0      F
13  14   22.0  34.0      F
14  15   26.0  38.0      F
15  16   26.0  37.0      F
16  17   25.0  38.0      F
17  18   26.0  37.0      F
18  19   28.0  40.0      F
19  20   23.0  35.0      F

## Calculations

In [19]:
# Goal: Create a new array and name it data_recarray.
data_recarray = data.to_records()
print(data_recarray)

# Goal: For each row of data calculate and store the w2h_ratio and shape.
w2h_ratios = data_recarray['Waist']/data_recarray['Hip']
#print(w2h_ratios)

# determine who is male (True) or female (False)
males = (data_recarray['Gender']=='M')

# males with w2h ration > 0.9 are apple shaped
male_apples = np.logical_and((w2h_ratios>0.9),males)

# females with w2h ratio > 0.8 are apple shaped
female_apples = np.logical_and((w2h_ratios>0.8),np.logical_not(males))

# combines the male_apples and female_apples
apples=np.logical_or(male_apples,female_apples)

# works like an if then else statement
shapes=np.where(apples,'Apple','Pear')

# The code below creates a new results array 

# add the two new columns to the dtype descriptor
dt = np.dtype(data_recarray.dtype.descr + [('W2H Ratio',float),('Shape','U5')])

# create a new results array with the same number of data_recarray and the new dtype
results = np.zeros(data_recarray.shape,dtype=dt)

## copy over the data_recarray data
for c in data_recarray.dtype.names:
    results[c]=data_recarray[c]
    
# add the two new columns
results['W2H Ratio']=w2h_ratios
results['Shape']=shapes

# Now, we show the data! (In a variety of formats.)
newdata = pd.DataFrame(results)
#print(newdata)
newdata.style
newdata.to_html("StatsResults.html")
newdata.to_csv("StatsResults.csv")

[( 0,  1,  30.,  32., 'M') ( 1,  2,  32.,  37., 'M')
 ( 2,  3,  30.,  36., 'M') ( 3,  4,  33.,  39., 'M')
 ( 4,  5,  29.,  33., 'M') ( 5,  6,  32.,  38., 'M')
 ( 6,  7,  33.,  42., 'M') ( 7,  8,  30.,  40., 'M')
 ( 8,  9,  30.,  37., 'M') ( 9, 10,  32.,  39., 'M')
 (10, 11,  24.,  35., 'F') (11, 12,  25.,  37., 'F')
 (12, 13,  24.,  37., 'F') (13, 14,  22.,  34., 'F')
 (14, 15,  26.,  38., 'F') (15, 16,  26.,  37., 'F')
 (16, 17,  25.,  38., 'F') (17, 18,  26.,  37., 'F')
 (18, 19,  28.,  40., 'F') (19, 20,  23.,  35., 'F')]
    index  ID  Waist   Hip Gender  W2H Ratio  Shape
0       0   1   30.0  32.0      M   0.937500  Apple
1       1   2   32.0  37.0      M   0.864865   Pear
2       2   3   30.0  36.0      M   0.833333   Pear
3       3   4   33.0  39.0      M   0.846154   Pear
4       4   5   29.0  33.0      M   0.878788   Pear
5       5   6   32.0  38.0      M   0.842105   Pear
6       6   7   33.0  42.0      M   0.785714   Pear
7       7   8   30.0  40.0      M   0.750000   Pear
8       8   9   30.0  37.0      M   0.810811   Pear
9       9  10   32.0  39.0      M   0.820513   Pear
10     10  11   24.0  35.0      F   0.685714   Pear
11     11  12   25.0  37.0      F   0.675676   Pear
12     12  13   24.0  37.0      F   0.648649   Pear
13     13  14   22.0  34.0      F   0.647059   Pear
14     14  15   26.0  38.0      F   0.684211   Pear
15     15  16   26.0  37.0      F   0.702703   Pear
16     16  17   25.0  38.0      F   0.657895   Pear
17     17  18   26.0  37.0      F   0.702703   Pear
18     18  19   28.0  40.0      F   0.700000   Pear
19     19  20   23.0  35.0      F   0.657143   Pear

## Output

In [111]:
# Goal: pretty print the rows as an HTML table

# Note: this works, but we can do this much better with pandas
html_table = '<table><tr><th>'
html_table += "</th><th>".join(results.dtype.names)
html_table += '</th></tr>'
for row in results:
    html_table += "<tr><td>"
    html_table += "</td><td>".join(str(v) for v in row)
    html_table += "</td></tr>"
html_table += "</table>"

from IPython.display import HTML, display
display(HTML(html_table))

# Export to "StatsResults.csv"
np.savetxt("StatsResults.csv",results,fmt='%s',delimiter=',',header=','.join(results.dtype.names),comments="")

array([( 1,  30.,  32., 'M',  0.9375    , 'Apple'),
       ( 2,  32.,  37., 'M',  0.86486486, 'Pear'),
       ( 3,  30.,  36., 'M',  0.83333333, 'Pear'),
       ( 4,  33.,  39., 'M',  0.84615385, 'Pear'),
       ( 5,  29.,  33., 'M',  0.87878788, 'Pear'),
       ( 6,  32.,  38., 'M',  0.84210526, 'Pear'),
       ( 7,  33.,  42., 'M',  0.78571429, 'Pear'),
       ( 8,  30.,  40., 'M',  0.75      , 'Pear'),
       ( 9,  30.,  37., 'M',  0.81081081, 'Pear'),
       (10,  32.,  39., 'M',  0.82051282, 'Pear'),
       (11,  24.,  35., 'F',  0.68571429, 'Pear'),
       (12,  25.,  37., 'F',  0.67567568, 'Pear'),
       (13,  24.,  37., 'F',  0.64864865, 'Pear'),
       (14,  22.,  34., 'F',  0.64705882, 'Pear'),
       (15,  26.,  38., 'F',  0.68421053, 'Pear'),
       (16,  26.,  37., 'F',  0.7027027 , 'Pear'),
       (17,  25.,  38., 'F',  0.65789474, 'Pear'),
       (18,  26.,  37., 'F',  0.7027027 , 'Pear'),
       (19,  28.,  40., 'F',  0.7       , 'Pear'),
       (20,  23.,  35., 'F',  0.65714286, 'Pear')],
      dtype=[('ID', '<i8'), ('Waist', '<f8'), ('Hip', '<f8'), ('Gender', '<U1'), ('W2H Ratio', '<f8'), ('Shape', '<U5')])